spawn:
  x: -28
  y: 64
  z: 992
  world: world

minplayer: 5
scoretowin: 10

spawnrate_xp : 5
spawnrate_iron : 5
spawnlapis : false

chest_breakable : true
friendlyfire : false
nolapisneeded : true
timelimit : true
spawnmob : false
eternalday : true

