spawn:
  x: -28
  y: 64
  z: 992
  world: world

minplayer: 5
scoretowin: 10

spawnrate_xp: 5
spawnrate_iron: 5
spawnlapis: false

timelimit_enable: true
timelimit_time: 30

chest_breakable: true
friendlyfire: false
spawnmob: false
eternalday: true

healonpoint: true