name: TheTOwOwer
version: DEV
author: FloLeProto
main: com.floleproto.thetower.Main

commands:
  host:
    description: Send a message for all
  start:
    description: Start the countdown
  cancelstart:
    description: Stop the countdown
  save:
    description: Save the inventory (edit mode only)
  rules:
    description: Print the rules in the chat